apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.secretNamespace }}

  labels:
{{- range $key, $value := .Values.labels }}
    {{ $key }}: "{{ $value }}"
{{- end }}

  annotations:
{{- range $key, $value := .Values.annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
