# Namespace where the secret lives (usually argocd)
secretNamespace: argocd


# ---------------------------------------------------------
# Metadata to apply to the cluster secret.
# These directly influence:
#  - addon selection
#  - workload placement
#  - ApplicationSet filters
#  - GitOps automation
# ---------------------------------------------------------

labels: {}
  # workload-webstore: "true"
  # workload-webstore-env: "dev"
  # enable_ingress_nginx: "false"

annotations: {}